// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM5VNRYTNB5oQWLU5mjXQXJfeBVmDwYkw',
    appId: '1:92528656355:web:566b8c8ff9578dad9c2ad6',
    messagingSenderId: '92528656355',
    projectId: 'zetaton-d7578',
    authDomain: 'zetaton-d7578.firebaseapp.com',
    storageBucket: 'zetaton-d7578.appspot.com',
    measurementId: 'G-JG4B5KBKD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOC-_MFlJ4xcacmGzEUj_xc4q7ZBKAjP0',
    appId: '1:92528656355:android:1463992c2864b1d09c2ad6',
    messagingSenderId: '92528656355',
    projectId: 'zetaton-d7578',
    storageBucket: 'zetaton-d7578.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfP4l9hkKIM5WjhjmNOWOkrhB_adOG3R0',
    appId: '1:92528656355:ios:3d0292c9d5b5cf5f9c2ad6',
    messagingSenderId: '92528656355',
    projectId: 'zetaton-d7578',
    storageBucket: 'zetaton-d7578.appspot.com',
    iosClientId: '92528656355-2g61l572ud9s8a1eh6rkcslp5k2l2kjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.zetaton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfP4l9hkKIM5WjhjmNOWOkrhB_adOG3R0',
    appId: '1:92528656355:ios:3d0292c9d5b5cf5f9c2ad6',
    messagingSenderId: '92528656355',
    projectId: 'zetaton-d7578',
    storageBucket: 'zetaton-d7578.appspot.com',
    iosClientId: '92528656355-2g61l572ud9s8a1eh6rkcslp5k2l2kjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.zetaton',
  );
}
